sudo: false
language: node_js
addons:
  apt:
    packages:
      - redis-server
node_js:
  - 6
install:
  - npm install
script:
  - redis-cli version
  - npm test
  - npm run report-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)
