language: node_js
before_script:
  - sh -c "sudo redis-server start"
  - until ruby -rsocket -e '$stderr=File.open(File::NULL,"w"); TCPSocket.new("localhost",6379)'; do sleep 1; done
node_js:
  - 6
install:
  - npm install
script:
  - npm test
after_success:
  - bash <(curl -s https://codecov.io/bash)
