version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - redis
  consul:
    image: "consul:0.8.0"
    ports:
      - "8500:8500"
  linkerd:
    image: buoyantio/linkerd:1.1.3
    command: ['/config.yaml']
    links:
      - consul
    volumes:
      - ./linkerd.yml:/config.yaml
    ports:
      - 9990:9990
      - 4140:4140
    depends_on:
      - consul-registrator
  consul-registrator:
    image: gliderlabs/registrator:v7
    command: ['consul://consul:8500']
    links:
      - consul
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul

# TODO: Add nginx as load balancer
# nginx:
#   restart: always
#   build: ./nginx/
#   ports:
#     - "80:80"
#   volumes:
#     - /www/public
#   volumes_from:
#     - web
#   links:
#     - web:web
