version: '2'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  web:
    build:
      context: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      - redis

# TODO: Add nginx as load balancer
# nginx:
#   restart: always
#   build: ./nginx/
#   ports:
#     - "80:80"
#   volumes:
#     - /www/public
#   volumes_from:
#     - web
#   links:
#     - web:web
